"""empty message

Revision ID: 093b0c69113f
Revises: a10254a45544
Create Date: 2024-06-27 20:40:54.396445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '093b0c69113f'
down_revision = 'a10254a45544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=80), nullable=False))
        batch_op.drop_column('level')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill', sa.String(length=80), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.String(length=80), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('tool')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('skill')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('education')

    # ### end Alembic commands ###
