"""empty message

Revision ID: 0ff1ba8404f0
Revises: 093b0c69113f
Create Date: 2024-06-28 16:06:28.065950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ff1ba8404f0'
down_revision = '093b0c69113f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('count')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('count')

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
