"""empty message

Revision ID: 1bf8575a356c
Revises: d54931da3c21
Create Date: 2024-07-11 15:34:03.084713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '1bf8575a356c'
down_revision = 'd54931da3c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [column['name'] for column in inspector.get_columns('field_of_study')]

    with op.batch_alter_table('field_of_study', schema=None) as batch_op:
        if 'education_level_id' not in columns:
            batch_op.add_column(sa.Column('education_level_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key(None, 'education_level', ['education_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_of_study', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('education_level_id')

    # ### end Alembic commands ###
