"""empty message

Revision ID: 38e0ab7b5a9d
Revises: 1bf8575a356c
Create Date: 2024-07-16 20:45:08.724132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e0ab7b5a9d'
down_revision = '1bf8575a356c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_of_study', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'education_level', ['education_level_id'], ['id'])

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('field_of_study', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
