"""empty message

Revision ID: 452566520d71
Revises: edbb08098bc0
Create Date: 2024-08-25 00:28:17.501704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '452566520d71'
down_revision = 'edbb08098bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('industry',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('industry', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    with op.batch_alter_table('education_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])
        batch_op.drop_column('job_title')

    with op.batch_alter_table('field_of_study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])
        batch_op.drop_column('job_title')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'industry', ['industry_id'], ['id'])
        batch_op.drop_column('job_title')

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'industry', ['industry_id'], ['id'])
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('industry')

    with op.batch_alter_table('education_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('field_of_study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('industry_id')

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('industry_id')
    
    # ### end Alembic commands ###
