"""empty message

Revision ID: edbb08098bc0
Revises: 38e0ab7b5a9d
Create Date: 2024-07-23 19:04:07.161292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbb08098bc0'
down_revision = '38e0ab7b5a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=False))

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('industry')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
